# Generated by Django 2.2 on 2019-05-21 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_uimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uimage',
            name='Sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='document.AddUser'),
        ),
        migrations.AlterField(
            model_name='uimage',
            name='Receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='document.AddUser'),
        ),
    ]
