# Generated by Django 2.2 on 2019-05-21 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_ufiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufiles',
            name='File',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc'])]),
        ),
    ]
