# Generated by Django 2.2 on 2019-05-21 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20190522_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufiles',
            name='File',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator('pdf')]),
        ),
    ]
